dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  adobe_xd: ^2.0.1
  sizer: ^2.0.15
  flutter_svg: ^1.1.4
  responsive_sizer: ^3.1.0
  table_calendar: ^3.0.6
  intl: ^0.17.0
  group_button: ^5.2.2
    
